# Exploratory Analysis
Using MF sample data from the man the legend MiscellaneousStuff
https://github.com/MiscellaneousStuff/tlol

Using sqlite to load db files from MF_sample_data

In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3
import sqlalchemy as db
import json
from collections import defaultdict

In [29]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows', 500)

## Data Loading

In [25]:
def load_table(path, echo=False):
    engine = db.create_engine(f'sqlite:///{path}', echo=echo).connect()
    df = pd.read_sql_table('objects',engine)
    return df

In [24]:
df = load_table('MF_sample_data/EUW1-5514503149.db')
df.shape

(153782, 36)

In [56]:
with open('EUW1-5237530168.rofl.json', 'r') as f:
    tmp = json.load(f)
    f.close()

JSONDecodeError: Expecting value: line 17653 column 1 (char 1178679345)

## Exploration
Observations:
- time: timestamp of game in seconds
- obj_type: what data in row is referring to
    - most important is probably champs, but also has minions, jungle, etc
- obj_id and name: specific object
    - name and obj_id are 1-to-1
- no gold amount or items which is super unfortunate

In [26]:
df.head()

,game_id,time,obj_type,net_id,obj_id,name,health,max_health,max_mana,team,crit,critMulti,ap,armour,mr,movement_speed,is_alive,duration,position_x,position_y,position_z,prev_position_x,prev_position_y,prev_position_z,ability_haste,lethality,direction,experience,mana_regen,health_regen,transformation,is_moving,is_dashing,targetable,invulnerable,recallState
0,5514490345,2.003382,champs,1073741856,2500,missfortune,570.0,570.0,300.0,100,0.0,1.75,0.0,34.0,30.0,325.0,1,5.368874e+08,132.0,183.574799,402.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.608,0.75,-2.1436057774943666e-38,1,0,1,0,0
1,5514490345,2.003382,champs,1073741858,2514,olaf,575.0,575.0,316.0,200,0.0,1.75,0.0,41.0,32.0,350.0,1,9.903824e+27,14102.0,171.977707,14194.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.500,1.70,1011908736.0,1,0,1,0,0
2,5514490345,2.003382,champs,1073741862,2521,rakan,540.0,540.0,315.0,200,0.0,1.75,9.0,38.0,32.0,340.0,1,3.601337e-43,14054.0,171.977707,14492.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.750,1.00,2.802596928649634e-45,1,0,1,0,0
3,5514490345,2.003382,champs,1073741854,2496,kayn,585.0,585.0,410.0,100,0.0,1.75,0.0,44.0,32.0,345.0,1,9.903824e+27,664.0,182.132538,286.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.300,1.60,1011908736.0,1,0,1,0,0
4,5514490345,2.003382,champs,1073741857,2511,taric,575.0,575.0,300.0,100,0.0,1.75,0.0,52.0,32.0,340.0,1,-3.761697e-37,298.0,183.574799,676.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.700,1.20,-1.6243182837520708e-19,1,0,1,0,0

In [36]:
df['obj_type'].value_counts()

minions     56605
turrets     39153
champs      22023
others      18993
jungle      10505
missiles     6503
Name: obj_type, dtype: int64

In [37]:
df[df['obj_type']=='others']['name'].value_counts()

sru_plant_satchel                  5598
yellowtrinket                      3307
sru_plant_vision                   2909
__mul                              2733
l                                1335
@                               785
sru_crabward                        631
olafaxe                             359
jammerdevice                        304
t\rj                              239
akshanbasicattack                    90
vexq                                 68
planthawkshot                        62
akshanpassiveattack                  54
8!v                                 47
perks_arcanecomet_mis                41
akshanqmissile                       28
promocontroller                      27
vexbasicattack2                      26
vexbasicattack                       26
talentreapervfx                      25
akshaneorbitalcounterclockwise       22
|v                                 21
N/A                                  20
planthawkshotaudio                   20
vexpgloomattackmissile               19
%
                                  18
(
7                                 16
akshanqmissilereturn                 15
vexe                                 14
/0                                  14
boneplating_buckler2                 13
>t?                                 12
ksdarkharvestpickupmis               11
perkpresenceofmindvisualmissile      10
crestoftheancientgolemlines           8
akshanemissile                        7
runes_ksguardian_trail_mis            7
minion_t200l2s06n0034                 7
akshaneattack                         6
hpp?hpp?
                             6
tristanaskin21                        6
x
\t                               5
spell                                 4
w_cas_anim.anm                        4
perksoulfeastvisualmissile            4
vexpgloomattack                       3
blessingofthelizardelderlines         3
he other                              2
hx*8                              1
transitionblendtexture                1
Name: name, dtype: int64

In [32]:
df[df['name']=='missfortune']['obj_id'].value_counts()

2500    1457
Name: obj_id, dtype: int64

In [35]:
df[df['name']=='missfortune']

,game_id,time,obj_type,net_id,obj_id,name,health,max_health,max_mana,team,crit,critMulti,ap,armour,mr,movement_speed,is_alive,duration,position_x,position_y,position_z,prev_position_x,prev_position_y,prev_position_z,ability_haste,lethality,direction,experience,mana_regen,health_regen,transformation,is_moving,is_dashing,targetable,invulnerable,recallState
0,5514490345,2.003382,champs,1073741856,2500,missfortune,570.000000,570.000000,300.000,100,0.0,1.75,0.0,34.000000,30.000000,325.0,1,536887360.0,132.000000,183.574799,402.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,1.60800,0.75000,-2.1436057774943666e-38,1,0,1,0,0
32,5514490345,2.307895,champs,1073741856,2500,missfortune,570.000000,570.000000,300.000,100,0.0,1.75,0.0,34.000000,30.000000,325.0,1,536887360.0,132.000000,183.574799,402.000000,132.000000,183.574799,402.000000,0.0,0.0,0.0,0.000000,1.60800,0.75000,-2.1436057774943666e-38,1,0,1,0,0
70,5514490345,2.556392,champs,1073741856,2500,missfortune,570.000000,570.000000,300.000,100,0.0,1.75,0.0,34.000000,30.000000,325.0,1,536887360.0,132.000000,183.574799,402.000000,132.000000,183.574799,402.000000,0.0,0.0,0.0,0.000000,1.60800,0.75000,-2.1436057774943666e-38,1,0,1,0,0
116,5514490345,2.623144,champs,1073741856,2500,missfortune,570.000000,570.000000,300.000,100,0.0,1.75,0.0,34.000000,30.000000,325.0,1,536887360.0,132.000000,183.574799,402.000000,132.000000,183.574799,402.000000,0.0,0.0,0.0,0.000000,1.60800,0.75000,-2.1436057774943666e-38,1,0,1,0,0
162,5514490345,2.756637,champs,1073741856,2500,missfortune,570.000000,570.000000,300.000,100,0.0,1.75,0.0,34.000000,30.000000,325.0,1,536887360.0,132.000000,183.574799,402.000000,132.000000,183.574799,402.000000,0.0,0.0,0.0,0.000000,1.60800,0.75000,-2.1436057774943666e-38,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153112,5514490345,298.928925,champs,1073741856,2500,missfortune,773.249268,787.174988,626.625,100,0.0,1.75,0.0,44.126499,30.737499,325.0,1,536887360.0,10841.696289,49.651989,1458.866089,10846.976562,49.655628,1438.128174,0.0,0.0,0.0,903.326111,1.79975,0.94175,-2.1436057774943666e-38,1,0,1,0,0
153245,5514490345,299.190887,champs,1073741856,2500,missfortune,773.249268,787.174988,626.625,100,0.0,1.75,0.0,44.126499,30.737499,325.0,1,536887360.0,10841.696289,49.651989,1458.866089,10841.696289,49.651989,1458.866089,0.0,0.0,0.0,903.326111,1.79975,0.94175,-2.1436057774943666e-38,1,0,1,0,0
153379,5514490345,299.453033,champs,1073741856,2500,missfortune,773.720154,787.174988,626.625,100,0.0,1.75,0.0,44.126499,30.737499,325.0,1,536887360.0,10764.454102,49.511814,1436.245117,10841.696289,49.651989,1458.866089,0.0,0.0,0.0,903.326111,1.79975,0.94175,-2.1436057774943666e-38,1,0,1,0,0
153515,5514490345,299.700684,champs,1073741856,2500,missfortune,773.720154,787.174988,626.625,100,0.0,1.75,0.0,44.126499,30.737499,325.0,1,536887360.0,10691.942383,49.376915,1412.763428,10764.454102,49.511814,1436.245117,0.0,0.0,0.0,903.326111,1.79975,0.94175,-2.1436057774943666e-38,1,0,1,0,0
153648,5514490345,299.935181,champs,1073741856,2500,missfortune,774.191040,787.174988,626.625,100,0.0,1.75,0.0,44.126499,30.737499,325.0,1,536887360.0,10620.618164,49.287289,1375.591797,10764.454102,49.511814,1436.245117,0.0,0.0,0.0,903.326111,1.79975,0.94175,-2.1436057774943666e-38,1,0,1,0,0

In [39]:
df[df['obj_type']=='champs']['name'].value_counts()

rakan          6093
tristana       5465
kayn           3121
monkeyking     3035
missfortune    1457
olaf           1426
taric          1426
Name: name, dtype: int64

In [48]:
df[df['obj_type']=='champs'].drop_duplicates()['name'].value_counts()

monkeyking     1514
rakan          1449
tristana       1446
missfortune    1420
olaf           1419
kayn           1416
taric          1414
Name: name, dtype: int64

In [42]:
df[df['name']=='tristana']['time'].value_counts()

4.971546      15
65.019035     12
129.724243    12
5.312423      10
143.694244     8
              ..
37.244076      1
37.110584      1
36.977093      1
36.910347      1
2.003382       1
Name: time, Length: 1399, dtype: int64

In [47]:
df[(df['name']=='tristana') & (df['time'] > 4) & (df['time'] < 5)].head()

,game_id,time,obj_type,net_id,obj_id,name,health,max_health,max_mana,team,crit,critMulti,ap,armour,mr,movement_speed,is_alive,duration,position_x,position_y,position_z,prev_position_x,prev_position_y,prev_position_z,ability_haste,lethality,direction,experience,mana_regen,health_regen,transformation,is_moving,is_dashing,targetable,invulnerable,recallState
675,5514490345,4.024797,champs,1073741861,2519,tristana,559.0,559.0,250.0,200,0.0,1.75,0.0,32.0,30.0,325.0,1,3.601337e-43,14588.0,171.977707,14454.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.44,0.75,2.802596928649634e-45,1,0,1,0,0
676,5514490345,4.024797,champs,1073741861,2519,tristana,559.0,559.0,250.0,200,0.0,1.75,0.0,32.0,30.0,325.0,1,3.601337e-43,14588.0,171.977707,14454.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.44,0.75,2.802596928649634e-45,1,0,1,0,0
677,5514490345,4.024797,champs,1073741861,2519,tristana,559.0,559.0,250.0,200,0.0,1.75,0.0,32.0,30.0,325.0,1,3.601337e-43,14588.0,171.977707,14454.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.44,0.75,2.802596928649634e-45,1,0,1,0,0
678,5514490345,4.024797,champs,1073741861,2519,tristana,559.0,559.0,250.0,200,0.0,1.75,0.0,32.0,30.0,325.0,1,3.601337e-43,14588.0,171.977707,14454.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.44,0.75,2.802596928649634e-45,1,0,1,0,0
679,5514490345,4.024797,champs,1073741861,2519,tristana,559.0,559.0,250.0,200,0.0,1.75,0.0,32.0,30.0,325.0,1,3.601337e-43,14588.0,171.977707,14454.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.44,0.75,2.802596928649634e-45,1,0,1,0,0

In [46]:
df[(df['name']=='tristana') & (df['time'] > 4) & (df['time'] < 5)].drop_duplicates().shape

(9, 36)

In [49]:
df['team'].value_counts()

200    66321
100    63012
300    19155
0       5294
Name: team, dtype: int64

In [51]:
df[df['obj_type']=='champs'][['name','team']].value_counts()

name         team
rakan        200     6093
tristana     200     5465
kayn         100     3121
monkeyking   100     3035
missfortune  100     1457
olaf         200     1426
taric        100     1426
dtype: int64

In [53]:
df[df['team'].isin([0,300])][['team','name']].value_counts()

team  name
300   sru_plant_satchel             5598
      sru_razorbeakmini             3706
      sru_plant_vision              2909
0     __mul                         2733
      l                           1335
300   sru_murkwolfmini              1300
      sru_krugmini                  1098
      sru_krug                       854
      sru_red                        851
0     @                          785
300   sru_razorbeak                  732
      sru_murkwolf                   671
      sru_gromp                      453
      sru_blue                       354
      sru_krugminimini               241
0     t\rj                         239
300   sru_crab                       219
0     8!v                            47
300   spawnminiminikrug_mis           41
      promocontroller                 27
      sru_dragon_air                  26
0     |v                            21
300   spawnminikrug_mis               20
0     N/A                             20
300   sru_razorbeakbasicattack2       18
0     %
                             18
300   sru_razorbeakbasicattack        16
0     (
7                            16
300   sru_grompbasicattack            15
0     /0                             14
      boneplating_buckler2            13
      >t?                            12
      minion_t200l2s06n0034            7
      hpp?hpp?
                        6
300   sru_gromp_heal_mis               6
0     tristanaskin21                   6
      x
\t                          5
      w_cas_anim.anm                   4
      runes_ksguardian_trail_mis       4
      spell                            4
      he other                         2
      hx*8                         1
      transitionblendtexture           1
      vexpgloomattackmissile           1
dtype: int64

## Riot Timeline API data EDA

In [57]:
df = pd.read_json('timeline_tmp.json')
position_data = []
for i in range(len(df.iloc[4]['info'])):
    loopdata = df.iloc[4]['info'][i]['participantFrames']
    c = pd.DataFrame(pd.DataFrame.from_dict(loopdata).loc['position']).transpose()
    c['timestamp'] = df.iloc[4]['info'][i]['timestamp']
    position_data.append(c)
df = pd.concat(position_data)

In [58]:
df.head()

,1,2,3,4,5,6,7,8,9,10,timestamp
position,"{'x': 554, 'y': 581}","{'x': 557, 'y': 345}","{'x': 335, 'y': 269}","{'x': 194, 'y': 457}","{'x': 329, 'y': 650}","{'x': 14180, 'y': 14271}","{'x': 14176, 'y': 14506}","{'x': 14398, 'y': 14582}","{'x': 14539, 'y': 14394}","{'x': 14404, 'y': 14201}",0
position,"{'x': 4335, 'y': 11842}","{'x': 3001, 'y': 11275}","{'x': 4391, 'y': 11745}","{'x': 4386, 'y': 11911}","{'x': 394, 'y': 461}","{'x': 6099, 'y': 12437}","{'x': 11227, 'y': 13378}","{'x': 8809, 'y': 8732}","{'x': 11722, 'y': 4105}","{'x': 12280, 'y': 3350}",60024
position,"{'x': 2148, 'y': 12061}","{'x': 6936, 'y': 4607}","{'x': 7500, 'y': 7056}","{'x': 10893, 'y': 1570}","{'x': 10956, 'y': 1409}","{'x': 2058, 'y': 12678}","{'x': 7995, 'y': 9843}","{'x': 7598, 'y': 7730}","{'x': 11824, 'y': 2188}","{'x': 11939, 'y': 1579}",120049
position,"{'x': 1597, 'y': 10787}","{'x': 1166, 'y': 1692}","{'x': 7348, 'y': 6784}","{'x': 1556, 'y': 595}","{'x': 10714, 'y': 2437}","{'x': 1363, 'y': 11665}","{'x': 14340, 'y': 14391}","{'x': 7939, 'y': 7101}","{'x': 11576, 'y': 1934}","{'x': 13383, 'y': 11544}",180071
position,"{'x': 4148, 'y': 13085}","{'x': 3131, 'y': 8406}","{'x': 3442, 'y': 2793}","{'x': 13737, 'y': 3704}","{'x': 13173, 'y': 3669}","{'x': 4146, 'y': 13592}","{'x': 11734, 'y': 4296}","{'x': 7728, 'y': 8393}","{'x': 14020, 'y': 4343}","{'x': 13228, 'y': 4202}",240077

In [67]:
with open('timeline_tmp.json','r') as f:
    timeline_tmp = json.load(f)
    f.close()

In [70]:
# each frame is interval of one minute
# get unique event types
event_types = set()
for frame in timeline_tmp['info']['frames']:
    for event in frame['events']:
        event_types.add(event['type'])

event_types

{'BUILDING_KILL',
 'CHAMPION_KILL',
 'CHAMPION_SPECIAL_KILL',
 'DRAGON_SOUL_GIVEN',
 'ELITE_MONSTER_KILL',
 'GAME_END',
 'ITEM_DESTROYED',
 'ITEM_PURCHASED',
 'ITEM_SOLD',
 'ITEM_UNDO',
 'LEVEL_UP',
 'OBJECTIVE_BOUNTY_PRESTART',
 'PAUSE_END',
 'SKILL_LEVEL_UP',
 'TURRET_PLATE_DESTROYED',
 'WARD_KILL',
 'WARD_PLACED'}

In [73]:
def round_timestamp(x, base=60000):
    return base * round(x/base)

In [94]:
events_reframe = defaultdict(list)
participants_reframe = pd.DataFrame()
frame_interval = timeline_tmp['info']['frameInterval']
for frame in timeline_tmp['info']['frames']:
    # timestamp = round_timestamp(frame['timestamp'], base=frame_interval)
    timestamp = round_timestamp(frame['timestamp'], base=10000)
    for event in frame['events']:
        event['sampleTimestamp'] = timestamp
        events_reframe[event['type']].append(event)
    for participant_id, participant_frame in frame['participantFrames'].items():
        tmp = pd.json_normalize(participant_frame, sep='_')
        tmp['participantId'] = participant_id
        tmp['sampleTimestamp'] = timestamp
        participants_reframe = pd.concat([participants_reframe, tmp], ignore_index=True)
participants_reframe = participants_reframe.set_index(['participantId','sampleTimestamp']).reset_index()

In [102]:
events_reframe_dfs = {}
for event_type, event_dict in events_reframe.items():
    events_reframe_dfs[event_type] = pd.DataFrame.from_dict(event_dict)
    fname = event_type.lower()
    events_reframe_dfs[event_type].to_pickle(f'data_checkpoints/event_{fname}.pkl')

In [104]:
participants_reframe.to_pickle('data_checkpoints/participant_stats.pkl')